version: "3.9"

services:
  mongodb:
    image: mongo:5.0.9
    container_name: education-system-mongodb
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    restart: always
    environment:
      MONGODB_DATABASE: ${MONGO_DB_NAME}
