spring:
  jpa:
    hibernate:
      ddl-auto: none
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}/${MONGO_DB_NAME}?retryWrites=true&w=majority
logging:
  level:
    org.hibernate:
      SQL: error
      type.descriptor.sql.BasicBinder: error

EMAIL_SENDER_USERNAME: ${EMAIL_SENDER_USERNAME}
EMAIL_SENDER_PASSWORD: ${EMAIL_SENDER_PASSWORD}
