spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST}:${MONGO_PORT}/${MONGO_DB_NAME}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties.hibernate:
      generate_statistics: true
      session:
        events.log.LOG_QUERIES_SLOWER_THAN_MS: 1
logging:
  level:
    org.hibernate.stat: DEBUG

server:
  error:
    include-message: always

email:
  sender:
    username: ${EMAIL_SENDER_USERNAME}
    password: ${EMAIL_SENDER_PASSWORD}
cors:
  origins: ${CORS_ORIGIN}
